# Generated by Django 3.2.3 on 2021-05-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rols',
            fields=[
                ('rolId', models.AutoField(primary_key=True, serialize=False)),
                ('rolName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=200)),
                ('rol', models.CharField(max_length=200)),
                ('photoFileName', models.CharField(max_length=200)),
            ],
        ),
    ]
